server:
  port: 9999

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xdb

  data:
    redis:
      port: 6379
      host: localhost

logging:
  level:
    com.langtu: debug

mybatis-plus:
  mapper-locations: classpath:mappersys\*.xml